---
# - name: Add Vivaldi Repository
- apt_repository:
    repo: "deb https://repo.vivaldi.com/stable/deb/ stable main"
    state: present
  tags:
    - vivaldi
  become: yes

# - name: Add the Vivaldi APT key
- apt_key:
    id: 6D3789EDC3401E12
    url: https://repo.vivaldi.com/stable/linux_signing_key.pub
    state: present
  tags:
    - vivaldi
  become: yes

# - name: Install Vivaldi
- apt:
    name: vivaldi-stable
    update_cache: yes
    state: latest
  tags:
    - vivaldi
  become: yes
